CMPG323_Project2/Controllers/GalleryController.cs
using CMPG323_Project2.Models;
using ImageGallery.Data;
using ImageGallery.Data.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMPG323_Project2.Controllers
{
    public class GalleryController : Controller
    {

        private readonly IImageService _iImageService;
        private readonly ImageGalleryDbContext _ctx;

  
        public GalleryController(IImageService iImageService, ImageGalleryDbContext ctx)
        {
            _iImageService = iImageService;
            _ctx = ctx;
        }


        public IActionResult Index()
        {
            var imageList = _iImageService.GetAll();
            var model = new GalleryIndexModel()
            {
                Images = imageList,
                SearchQuery = ""
            };
            return View(model);

        }

        public IActionResult Detail(int id)
        {
            var image = _iImageService.GetById(id);
            var model = new GalleryDetailModel()
            {
                Id = image.Id,
                Created = image.Created,
                Url = image.Url,
                Title = image.Title,
                Tags = image.Tags.Select(x => x.Description).ToList(),
                Geolocation = image.Geolocation,
                CapturedBy = image.CapturedBy,
                CapturedDate = image.CapturedDate
            };

            return View(model);


        }



        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var images = await _ctx.GalleryImages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (images == null)
            {
                return NotFound();
            }

            return View(images);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var images = await _ctx.GalleryImages.FindAsync(id);
            try
            {
                if (images.Url != null)
                {
                    _ctx.GalleryImages.Remove(images);
                    await _ctx.SaveChangesAsync();
                }
            }catch(Exception)
            {
                throw;
            }
            
            
            return RedirectToAction(nameof(Index));
        }



        // GET: Images/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var images = await _ctx.GalleryImages.FindAsync(id);
            if (images == null)
            {
                return NotFound();
            }
            return View(images);
        }

        // POST: Images/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Created,Url,Geolocation,CapturedDate,CapturedBy,Tags")] GalleryImage images)
        {
            if (id != images.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (images.Url != null)
                    {
                        _ctx.Update(images);
                        await _ctx.SaveChangesAsync();
                    }
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (id != (images.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(images);
        }
    }
}

CMPG323_Project2/Views/Gallery/Delete.cshtml
@model ImageGallery.Data.Models.GalleryImage;

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Images</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class="col-sm-10">
        <img src="@Url.Content(Model.Url)" alt="Image" style="width: 150px; height: 220px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Geolocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Geolocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CapturedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapturedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CapturedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CapturedBy)
        </dd>


    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Gallery</a>
    </form>
</div>

CMPG323_Project2/Views/Gallery/Detail.cshtml
@model CMPG323_Project2.Models.GalleryDetailModel

<div class="container card-body-content">
    <div class="row image-detail-container">
        <div class="image-detail">
            <img src="@Model.Url" alt="@Model.Title" />
        </div>
    </div>
    <div class="row image-detail-meta">
        <span> Title: @Model.Title &nbsp;</span>
        <span> Uploaded: @Model.Created &nbsp;</span>
        <span> Geolocation: @Model.Geolocation &nbsp;</span>
        <span> Captured date: @Model.CapturedDate &nbsp;</span>
        <span> Captured by: @Model.CapturedBy </span>
    </div>
    <div class="row controlls">
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Index">Back To Gallery </a>
        &nbsp;
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
        &nbsp;
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    </div>

</div>

CMPG323_Project2/Views/Gallery/Edit.cshtml
@model ImageGallery.Data.Models.GalleryImage;

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Images</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Geolocation" class="control-label"></label>
                <input asp-for="Geolocation" class="form-control" />
                <span asp-validation-for="Geolocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tags" class="control-label"></label>
                <input asp-for="Tags" class="form-control"/>
                <span asp-validation-for="Tags" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapturedDate" class="control-label"></label>
                <input asp-for="CapturedDate" class="form-control" />
                <span asp-validation-for="CapturedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapturedBy" class="control-label"></label>
                <input asp-for="CapturedBy" class="form-control" />
                <span asp-validation-for="CapturedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Url" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Gallery</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/custom-validation.js"></script>
}

CMPG323_Project2/Views/Gallery/Index.cshtml
@model CMPG323_Project2.Models.GalleryIndexModel

<div class="container body-content">
    <div class=" row gallery-content">
        @foreach (var image in Model.Images)
        {
            <div class="gallery-image-container drop-shadow">
                <a asp-controller="Gallery" asp-action="Detail" asp-route-id="@image.Id">
                    <div class="gallery-image" style="background-image:url(@image.Url)"></div>
                </a>

            </div>


        }

    </div>
</div>