CMPG323_Project2/Controllers/ImageController.cs
using CMPG323_Project2.Infrastructures;
using CMPG323_Project2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CMPG323_Project2.Controllers
{
    public class ImageController : Controller
    {
        private readonly ICloudinaryImageUpload _imageUpload;

        public ImageController(ICloudinaryImageUpload imageUpload)
        {
            _imageUpload = imageUpload;
        }

        [Authorize]
        public IActionResult Upload()
        {
            var model = new UploadImageModel();

            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> UploadNewImage(UploadImageModel model)
        {

            await _imageUpload.UploadPicture(model);
            return RedirectToAction("Index", "Gallery");

        }
    }
}

CMPG323_Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMPG323 Project 2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Gallery" asp-action="Index">CMPG323 Project 2</a>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Image" asp-action="Upload">Upload</a></li>
                    </ul>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a id="qsLogoutBtn" asp-controller="Account" asp-action="LogOut">Logout</a></li>
                    }
                    else
                    {
                        <li><a id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CMPG323 Project 2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>